env:

    SPAM: https://raw.githubusercontent.com/XelXen/Ubuntu-Tmate/master/spam.sh 

task:

  name: "CIRRUX BUILDER"

  timeout_in: 1440m  

  container:

      image: ubuntu:20.04

      cpu: 8

      memory: 32G

        

  Setup_script:

       - export DEBIAN_FRONTEND=noninteractive

       - apt update

       - apt install sudo

       - df -h

       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

       - apt-get install -y tzdata

       - dpkg-reconfigure --frontend noninteractive tzdata

       - sudo apt update -y

       - sudo apt install software-properties-common -y

       - sudo add-apt-repository ppa:openjdk-r/ppa -y

       - sudo apt-get install python3 -y

       - sudo apt-get install git -y

       - sudo apt-get install gnupg -y

       - sudo apt-get install flex -y 

       - sudo apt-get install bison -y 

       - sudo apt-get install wget -y 

       - sudo apt-get install python-is-python3 -y 

       - sudo apt-get install build-essential -y 

       - sudo apt-get install zip -y 

       - sudo apt-get install curl -y 

       - sudo apt-get install zlib1g-dev -y 

       - sudo apt-get install gcc-multilib -y 

       - sudo apt-get install g++-multilib -y 

       - sudo apt-get install libc6-dev-i386 -y 

       - sudo apt-get install lib32ncurses5-dev -y 

       - sudo apt-get install x11proto-core-dev -y 

       - sudo apt-get install libx11-dev -y 

       - sudo apt-get install lib32z1-dev -y 

       - sudo apt-get install libgl1-mesa-dev -y 

       - sudo apt-get install libxml2-utils -y 

       - sudo apt-get install xsltproc -y 

       - sudo apt-get install unzip -y

       - sudo apt-get install fontconfig -y

       - sudo apt-get install clang -y

       - sudo apt-get install ccache -y

       - sudo apt-get install git -y

       - sudo apt-get install aria2 -y

       - sudo apt-get install nano -y

       - sudo apt-get install screen -y

       - sudo apt-get install xclip -y

       - sudo apt-get install silversearch* -y

       - git config --global user.name "XelXen"

       - git config --global user.email "xelxenfox@gmail.com"

       - mkdir ~/bin

       - PATH=~/bin:$PATH

       - cd ~/bin

       - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo

       - chmod a+x ~/bin/repo

       - git clone https://github.com/akhilnarang/scripts.git ~/scripts

       - cd ~/scripts

       - sudo bash setup/android_build_env.sh

       - cd ~ 

  

  Spam_script:

      - wget -P /tmp $SPAM

      - sh '/tmp/spam.sh'

